---
title: ""
---
<br>

## Latest News

<br>

#### <b> 26th January 2021 </b>
##### Alice will be attending a CEDR Workplace mediation conversion course to add to her existing civil and commercial mediation accreditation.

<br>

#### <b> December 2020 </b>
##### Alice joined the Civil Mediation Council.

<br>

#### <b> 13th November 2020 </b>
##### <b>ENAEX International Trade Conference Brazil – CAAEB Panel on Mediation in Agribusinesses UK and Brazil</b>. Lead speaker and joined on the panel by Luiz Roberto Barcellos; President of the Brazilian Fresh Fruit Growers and Exporters Association – ABRAFRUTAS and Ary Rogerio Moura; Commercial Manager for Sipal, Brazil

<br>

#### <b> 13-14th October 2020 </b>
##### Alice attended a course with the Centre for Coaching a Certificate in Coaching Supervision. Written element submitted, fingers crossed, we can expect to hear in February 2021. A great way to develop both coaching and supervision skills and gain insight and practical experience to deliver professional supervision to developing coaches with much to take across into mediation.

<br>

#### <b> October 2020 </b>
##### Nominated and awarded for customer satisfaction in mediation.

<br>

#### <b> 6-9th September 2020 </b>
##### 10th International Congress of ISCP across the three days of events. Alice was delighted to deliver a poster for a paper co-written with Dr Siobhain O’Riordan CPsychol FISCP with the snappy title “Positive psychology and coaching within the Welsh livestock farming sector: exploring the relationship with profitability and productivity when set against the sustainable future of farm businesses and the environment”.

<br>