---
title: ""
---
<br>

#### <b> Nerys Llewellyn Jones </b>
##### Managing partner at Agri Advisor
<h6> Alice is an effective mediator who puts in maximum effort to assist parties achieve a mediated settlement of their own design. She understands the practicalities and the importance of getting a workable solution for all concerned for the longer term. I never hesitate in putting her forward as a mediator for my client's dispute nor in recommending her to others. </h6>

<br>

#### <b> Anthony Geddes </b>
##### Wales Confor
<h6> I have had the pleasure of attending events where Alice has been a contributor or a chair and have always been impressed with her ability to draw people into the discussion whilst keeping them focused on achieving outcomes. Her capable and direct approach to dealing with people and the topics of discussion or disagreement is refreshing and an invaluable skill.
<br><br>
When I approached Alice to coach me, I once again found her professional and insightful. Her ability to listen, assess a situation and talk clearly and directly on a one to one basis produces good results. This coupled to a wealth of experience in farming, family and working life really gives her a edge in understanding each potential driver in a situation.
<br><br>
It is a pleasure to recommend Alice and I look forward to continuing to work with her. </h6>

<br>

#### <b> Murray Pullin </b>
<h6> In business, and personal life, it is easy to get bogged down one problem that can impact how you manage other events in business or your life. Alice gave me some coaching to help me gain perspective on some challenges that I faced. Alice's knowledge and techniques delivered positive results for me that I can use again and again. For that, I would strongly recommend Alice and her coaching. </h6>

<br>

#### <b> Catherine Orton </b>
##### BW
<h6> Alice is a highly motivated individual, with both strategic and practical out of the box powers of assessment, analysis and decision making, coupled with insightful people skills. Her life and career experience has produced a broad and deep knowledge of Food, Agriculture and associated sectors, and now delivers an innovative and quality experience to her Rural Business clients. I have witnessed Alice's relaxed confidence and driven attitudinal approach thrive in the Agrisgôp environment where she has been able to capitalize on extensive subject knowledge and contact network. An inspiring and engaging professional! </h6>

<br>

#### <b> Alison Harvey </b>
<h6> I have had the good fortune of working with Alice as part of the women in agriculture group in Lampeter. Through this group she has driven us to think and to have purpose, this in turn has given us confidence and we continue to meet as a group and to learn. </h6>

<br>

#### <b> Wendy Jenkins <b>
##### Cymru Agricultural & Rural AdviceLtd
<h6>The Lampeter Women in Agriculture group has developed into a group that has benefited all us a great deal, in terms of building confidence and getting our views heard. This would not have happened without Alice’s skills as the group facilitator. She organised, encouraged, and more importantly challenged all of us to participate actively within the group. </h6>



